### ISSUE TITLE
Render problem in Edge

### ISSUE THREAD

**Issue by rafaelfernandezgis** [rubenmoya/airship-test#1]
If clone the project and then start it on localhost:3000, it renders fine in Chrome and Firefox but not in Microsoft Edge.
Just in case it helps, I had a similar problem in my React project. It came from a SVG object. In this case, maybe it is just a html object too.

**Comment by rubenmoya** [comment]
Hi @rafaelfernandezgis, thank you for reporting it, could you share a screenshot, please?

**Comment by rafaelfernandezgis** [comment]
Forget it about, maybe it was just my internet connection. Now it works fine for Edge, Chrome and Firefox. Good job man!

Sorry for the interruption :-|

**Comment by rubenmoya** [comment]
No problem, I'm glad it's working :)
