### ISSUE TITLE
Range component implementation on a legend

### ISSUE THREAD

**Issue by rafaelfernandezgis** [rubenmoya/airship-test#2]
Hi there, I'm trying to implement the Range airship component into a legend to change a layer transparency value. Also I'm using the 'react-leaflet-control' extension to render components in the map container.
The problem is I can see the Range component, but I can't drag the slider. I suspect it's because of the mouse over Propagation 'react-leaflet-control' has already implement.

If I put the Range component on a regular DIV (without 'react-leaflet-control') then I can drag both, slider and map, as a block In this specific case, I'd need to disable the propagation.

Can you please take a look at this behavior? Maybe by using props to enable or disable propagation would be great.

Thx!

**Comment by rubenmoya** [comment]
Hi @rafaelfernandezgis, thank you for reporting it!

Do you mind opening the issue in https://github.com/CartoDB/airship which is the official repository? This is just a demo app built with it.

I'll have a look into it and see what's going on.

**Comment by rafaelfernandezgis** [comment]
Sure thing!
